### ISSUE TITLE
Cluster Deployment Checklist

### ISSUE THREAD

**Issue by onudson** [onudson/cits#9]
This Cluster Deployment Checklist has been developed to facilitate in location preparation and installation.  

Requirements Gathering
- [ ] Does the hardware meet the need of the application(s) it will be hosting?
- [ ] What are the communication expectations of the stakeholders throughout the deployment?
- [ ] Is there a timeline dictating the completion of the cluster installation and availability?

Server Room Power
- [ ] Identify output from UPS, 208v or 120v?  Amperage per circuit?
- [ ] Calculate new load and estimate for UPS capacity in the event of building power failure
- [ ] Identify remaining life span of UPS and batteries
- [ ] Gather wattage consumption of servers and switches to calculate load capacity per pdu
- [ ] Match server and PDU cable ends with outlet receptacles
- [ ] Estimate power cable lengths needed
- [ ] If remote power control is desired, plan for smart PDU configuration 

Server Room Cooling and Humidity
- [ ] Gather BTU/hour output of all servers to calculate total room worst case scenario
- [ ] Gather existing cooling capacity
- [ ] Identify cooling design of room to dictate arrangement of servers in racks.  If ambient air cooled, leave air gaps in between servers.
- [ ] Deploy temperature and humidity monitors

Networking
- [ ] Identify need for dual switch PSUs
- [ ] Identify need for bandwidth capacity & cable/receiver form factors (e.g. RJ45 or SFP+)
- [ ] Identify quantity of switch ports needed to host all cluster server NICs
- [ ] Identify vlans, IP addresses, and hostnames for all cluster components (e.g. servers, switches, smart PDUs)
- [ ] Estimate network cable lengths needed
- [ ] Gather cable making equipment and supplies if needed

Delivery Logistics
- [ ] Is there a loading dock available?
- [ ] Are there personnel available to help move boxes?
- [ ] Is there a dolly or cart available for moving boxes?
- [ ] Is there an elevator available with the weight capacity to handle pallets of computer hardware?
- [ ] Is the route to/from the elevator clear and able to navigate with a large pallet on a pallet jack?

Waste Disposal
- [ ] Is there a location identified to store the boxes and packing foam prior to disposal?
- [ ] Are recycling facilities available to receive cardboard and plastics?  Hours of availability? 

Personnel Safety
- [ ] Obtain comfortable ear protection 
- [ ] Obtain respiratory masks if necessary during 100 year pandemic
- [ ] Dress in comfortable layers which won't snag on equipment
- [ ] Plans for breaks to stretch, eat, and exercise

Miscellaneous Tools and Supplies
- [ ] Obtain velcro strips for cable management
- [ ] Obtain label maker with laminated label tape
- [ ] Have on hand a box cutter, screwdrivers, camera
- [ ] Property tags if required by organization
- [ ] Printed invoice to track property tags and serial numbers as servers are racked
